<?xml version="1.0"?>
<robot name="podcar" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:include filename="$(find pod2_description)/xacro/body.gazebo.xacro" />
  
  <!--######### base link/chassis ###-->
  <xacro:macro name="podcar_base" params="name">
    <xacro:property name="depth" value="1.6"/>
    <xacro:property name="height" value="1.62"/>
    <xacro:property name="width" value="0.73"/>
    <xacro:property name="base_mass" value="160"/>
    <xacro:property name="clearance" value="0.06"/>

    <xacro:property name = "wheelbase" value="1.686"/>
    
    <link name="base_footprint">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>
    </link>
    
    <joint name="base_link_joint" type="fixed">
      <origin xyz="${wheelbase / 2} 0 0" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>
    
    <link name="base_link"/>
       <inertial>
          <mass value="33.855"/>
          <origin xyz="-0.0856132 -0.000839955 0.238145" rpy=" 0 0 0"/>
          <inertia>
            <ixx>2.2343</ixx>
            <ixy>-0.023642</ixy>
            <ixz>0.275174</ixz>
            <iyy>3.42518</iyy>
            <iyz>0.00239624</iyz>
            <izz>2.1241</izz>
          </inertia>
       </inertial>
       <collision>
          <origin xyz="0 0 0.25" rpy=" 0 0 0"/>
          <geometry>
            <mesh filename="package://pod2_description/meshes/base_link.stl"/>
          </geometry>
       </collision>
       <visual>
          <origin xyz ="0 0 0" rpy="0 0 1.57079"/>
          <geometry>
            <mesh filename="package://pod2_description/meshes/podcarv3.dae" scale="65 69 69"/>
            <!-- <scale>65 69 69</scale> -->
          </geometry>
       </visual>
    </link>
  </xacro:macro>
</robot>
   
   
       
       
   
