<?xml version="1.0">
<robot name="wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name = "rear_tyre_radius" value=="0.165"/>
  <xacro:property name = "back_wheel_mass" value="2.6357"/>
  <xacro:property name = "back_tyre_width" value="0.130"/>

  <xacro:property name = "front_tyre_radius" value="0.165"/>
  <xacro:property name = "front_wheel_mass" value="2.6357"/>
  <xacro:property name = "front_tyre_width" value="0.130"/>

  <xacro:property name = "friction_dry_mu" value="0.95"/>
  <xacro:property name = "friction_wet_mu" value="0.4"/>

  <xacro:property name = "degrees_90" value="1.57079633"/>
  <xacro:property name = "degrees_180" value="3.14159265"/>

  <xacro:property name = "wheelbase" value="1.4"/>
  <xacro:property name = "track" value="0.8"/>
  
  <gazebo reference="front_left_wheel">
    <mu1 value="${friction_dry_mu}"/>
    <mu2 value="${friction_dry_mu}"/>
    <minDepth>0.005</minDepth>
    <kp>1e8</kp>
    <material>Gazebo/Black</material>
  </gazebo>
  
  <gazebo reference="front_right_wheel">
    <mu1 value="${friction_dry_mu}"/>
    <mu2 value="${friction_dry_mu}"/>
    <minDepth>0.005</minDepth>
    <kp>1e8</kp>
    <material>Gazebo/Black</material>
  </gazebo>
  
  <gazebo reference="back_left_wheel">
    <mu1 value="${friction_dry_mu}"/>
    <mu2 value="${friction_dry_mu}"/>
    <minDepth>0.005</minDepth>
    <kp>1e8</kp>
    <material>Gazebo/Black</material>
  </gazebo>
  
  <gazebo reference="back_right_wheel">
    <mu1 value="${friction_dry_mu}"/>
    <mu2 value="${friction_dry_mu}"/>
    <minDepth>0.005</minDepth>
    <kp>1e8</kp>
    <material>Gazebo/Black</material>
  </gazebo>
  
  <link name="front_left_wheel">
    <inertial>
      <mass value="${front_wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="${(1 / 12)*front_wheel_mass*(3*(front_tyre_radius*front_tyre_radius)+ front_tyre_width * front_tyre_width)}" ixy="0.0" ixz="0.0"
               iyy="${(1 / 12)*front_wheel_mass*(3*(front_tyre_radius*front_tyre_radius)+ front_tyre_width * front_tyre_width)}" iyz="0.0"
               izz="${(1/2)*front_wheel_mass*front_tyre_radius*front_tyre_radius}"/>
    </inertial>
    <collision name="front_left_wheel_collision">
      <geometry>
        <cylinder radius="${front_tyre_radius}" length="${front_tyre_width}"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder radius="${front_tyre_radius}" length="${front_tyre_width}"/>
      </geometry>
      <material name="tire_mat"/>
    </visual>
  </link>
  
  <link name="front_right_wheel">
    <inertial>
      <mass value="${front_wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="${(1 / 12)*front_wheel_mass*(3*(front_tyre_radius*front_tyre_radius)+ front_tyre_width * front_tyre_width)}" ixy="0.0" ixz="0.0"
               iyy="${(1 / 12)*front_wheel_mass*(3*(front_tyre_radius*front_tyre_radius)+ front_tyre_width * front_tyre_width)}" iyz="0.0"
               izz="${(1/2)*front_wheel_mass*front_tyre_radius*front_tyre_radius}"/>
    </inertial>
    <collision name="front_right_wheel_collision">
      <geometry>
        <cylinder radius="${front_tyre_radius}" length="${front_tyre_width}"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder radius="${front_tyre_radius}" length="${front_tyre_width}"/>
      </geometry>
      <material name="tire_mat"/>
    </visual>
  </link>
  
  <link name="back_left_wheel">
    <inertial>
      <mass value="${back_wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="${(1 / 12)*back_wheel_mass*(3*(back_tyre_radius*back_tyre_radius)+ back_tyre_width * back_tyre_width)}" ixy="0.0" ixz="0.0"
               iyy="${(1 / 12)*back_wheel_mass*(3*(back_tyre_radius*back_tyre_radius)+ back_tyre_width * back_tyre_width)}" iyz="0.0"
               izz="${(1/2)*back_wheel_mass*back_tyre_radius*back_tyre_radius}"/>
    </inertial>
    <collision name="back_left_wheel_collision">
      <geometry>
        <cylinder radius="${back_tyre_radius}" length="${back_tyre_width}"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder radius="${back_tyre_radius}" length="${back_tyre_width}"/>
      </geometry>
      <material name="tire_mat"/>
    </visual>
  </link>
  
  <link name="back_right_wheel">
    <inertial>
      <mass value="${back_wheel_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="${(1 / 12)*back_wheel_mass*(3*(back_tyre_radius*back_tyre_radius)+ back_tyre_width * back_tyre_width)}" ixy="0.0" ixz="0.0"
               iyy="${(1 / 12)*back_wheel_mass*(3*(back_tyre_radius*back_tyre_radius)+ back_tyre_width * back_tyre_width)}" iyz="0.0"
               izz="${(1/2)*back_wheel_mass*back_tyre_radius*back_tyre_radius}"/>
    </inertial>
    <collision name="back_right_wheel_collision">
      <geometry>
        <cylinder radius="${back_tyre_radius}" length="${back_tyre_width}"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <cylinder radius="${back_tyre_radius}" length="${back_tyre_width}"/>
      </geometry>
      <material name="tire_mat"/>
    </visual>
  </link>
  
  <link name="front_left_pivot">
    <inertial>
      <mass value="2.6357"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0246688" ixy="0.0" ixz="0.0" iyy="0.0246688" iyz="0.0" izz="0.0246688"/>
    </inertial>
  </link>
  
  <link name="front_right_pivot">
    <inertial>
      <mass value="2.6357"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0246688" ixy="0.0" ixz="0.0" iyy="0.0246688" iyz="0.0" izz="0.0246688"/>
    </inertial>
  </link>
  
  <link name="trackingrod">
    <inertial>
      <mass value="2.6357"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0246688" ixy="0.0" ixz="0.0" iyy="0.0246688" iyz="0.0" izz="0.0246688"/>
    </inertial>
  </link>
  
  <joint name="tracking_left_pivot_joint" type="revolute">
    <parent link="trackingrod"/>
    <child link="front_left_pivot"/>
    <origin xyz="-.1 0 0" rpy="0 0 0">
    <axis xyz="0 0 1"/>
    <limit lower="-0.785398" upper="0.785398" effort="500000" velocity="250"/>
  </joint>
  
  <joint name="tracking_right_pivot_joint" type="revolute">
    <parent link="trackingrod"/>
    <child link="front_right_pivot"/>
    <origin xyz="-.1 0 0" rpy="0 0 0">
    <axis xyz="0 0 1"/>
    <limit lower="-0.785398" upper="0.785398" effort="500000" velocity="250"/>
  </joint>
  
  
    
  
  
  <xacro:macro name="FL_wheel">
    <joint name="front_left_pivot_joint" type="revolute">
      <parent link="base_link"/>
      <child link="front_left_pivot"/>
      <origin xyz="${wheelbase} ${-(track / 2)} 0" rpy="${degrees_90} 0 ${degrees_180}"/>
      <axis xyz="0 1 0"/>
      <limit lower="-0.785398" upper="0.785398" effort="500000" velocity="250"/>
    </joint>

    <joint name="front_left_wheel_joint" type="revolute">
      <parent link="front_left_pivot"/>
      <child link="front_left_wheel"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>
  </xacro:macro> 
  
  <xacro:macro name="FR_wheel">
    <joint name="front_right_pivot_joint" type="revolute">
      <parent link="base_link"/>
      <child link="front_right_pivot"/>
      <origin xyz="${wheelbase} ${-(track / 2)} 0" rpy="${degrees_90} 0 ${degrees_180}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.785398" upper="0.785398" effort="500000" velocity="250"/>
    </joint>

    <joint name="front_right_wheel_joint" type="revolute">
      <parent link="front_right_pivot"/>
      <child link="front_right_wheel"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>
  </xacro:macro> 
  
  <xacro:macro name="RL_wheel">
    <joint name="back_left_wheel_joint" type="revolute">
      <parent link="base_link"/>
      <child link="back_left_wheel"/>
      <origin xyz="0 ${-(track / 2)} 0" rpy="${degrees_90} 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="RR_wheel">
    <joint name="back_right_wheel_joint" type="revolute">
      <parent link="base_link"/>
      <child link="back_right_wheel"/>
      <origin xyz="0 ${(track / 2)} 0" rpy="${degrees_90} 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>
  </xacro:macro>
</robot>

  
  
  

      
